name: finger
description: A Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # Maps / Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^10.1.0

  # Biometrics
  local_auth: ^2.2.0

  # Image picking
  image_picker: ^1.0.7

  # Crop (Flutter native – المستخدم حاليًا)
  crop_your_image: ^1.1.0

  # File system
  path_provider: ^2.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
